# Generated by Django 4.0.5 on 2022-10-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='followers',
            new_name='follow',
        ),
    ]
